
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class com.faria.Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public com.faria.Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public com.faria.Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public com.faria.Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\013\000\002\002\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\014\000\004\005\005\001\002\000\004\002\016\001" +
    "\002\000\004\006\006\001\002\000\004\004\007\001\002" +
    "\000\004\011\010\001\002\000\004\004\011\001\002\000" +
    "\004\011\012\001\002\000\004\004\013\001\002\000\004" +
    "\007\014\001\002\000\004\010\015\001\002\000\004\002" +
    "\001\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\014\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$com.faria.Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$com.faria.Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$com.faria.Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$com.faria.Parser$actions {
  private final com.faria.Parser parser;

  /** Constructor */
  CUP$com.faria.Parser$actions(com.faria.Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$com.faria.Parser$do_action_part00000000(
    int                        CUP$com.faria.Parser$act_num,
    java_cup.runtime.lr_parser CUP$com.faria.Parser$parser,
    java.util.Stack            CUP$com.faria.Parser$stack,
    int                        CUP$com.faria.Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$com.faria.Parser$result;

      /* select the action based on the action number */
      switch (CUP$com.faria.Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // S ::= TRIANGULO PAR_OPEN NUMBER COMMA NUMBER COMMA NUMBER PAR_CLOSE SEMICOLON 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-6)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-6)).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-6)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-4)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-4)).right;
		String n2 = (String)((java_cup.runtime.Symbol) CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-4)).value;
		int n3left = ((java_cup.runtime.Symbol)CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-2)).left;
		int n3right = ((java_cup.runtime.Symbol)CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-2)).right;
		String n3 = (String)((java_cup.runtime.Symbol) CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-2)).value;
		
            int a = Integer.parseInt(n1);
            int b = Integer.parseInt(n2);
            int c = Integer.parseInt(n3);
            if((a+b>c) && (a+c>b) && (b+c>a))
                System.out.println("Is a triangle");
            else
                System.out.println("Not a triangle");
        
              CUP$com.faria.Parser$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-8)), ((java_cup.runtime.Symbol)CUP$com.faria.Parser$stack.peek()), RESULT);
            }
          return CUP$com.faria.Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-1)).value;
		RESULT = start_val;
              CUP$com.faria.Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$com.faria.Parser$stack.elementAt(CUP$com.faria.Parser$top-1)), ((java_cup.runtime.Symbol)CUP$com.faria.Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$com.faria.Parser$parser.done_parsing();
          return CUP$com.faria.Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$com.faria.Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$com.faria.Parser$do_action(
    int                        CUP$com.faria.Parser$act_num,
    java_cup.runtime.lr_parser CUP$com.faria.Parser$parser,
    java.util.Stack            CUP$com.faria.Parser$stack,
    int                        CUP$com.faria.Parser$top)
    throws java.lang.Exception
    {
              return CUP$com.faria.Parser$do_action_part00000000(
                               CUP$com.faria.Parser$act_num,
                               CUP$com.faria.Parser$parser,
                               CUP$com.faria.Parser$stack,
                               CUP$com.faria.Parser$top);
    }
}

}
