package com.faria;

import java_cup.runtime.*;
import com.faria.utils.DerivationTree;
import com.faria.utils.TabelaSimbolos;
import com.faria.utils.Token;
import com.faria.utils.AnalisadorSintatico;
import java.util.*;

parser code {: 
    TabelaSimbolos tb = new TabelaSimbolos();

    public String currentTipo = "";
    public String currentValor = "";

    // NOTA: Falta colocar "validarTipagem" dentro da GLC para fazer a validação, boa sorte!

    public void validarTipagem(String tipo, String valor, int line, int column) {
        // A lógica pesada foi movida para AnalisadorSintatico.java
        String erro = AnalisadorSintatico.validar(tipo, valor);
        if (erro != null) {
            this.defineError(line, column, erro);
        }
    }

    public void inserirSimbolo(int refSym, Object lexemaZ, int line, int column) {


        if(lexemaZ instanceof String){

            String lexema = (String) lexemaZ;

            Token token = new Token(refSym, lexema);

            tb.inserirSimbolo(lexema, token, line, column, getCodeinfoId());
        }

        // tb.imprimirTabela();
    }

    public void inserirSimbolo(int refSym, int line, int column) {
        Token token = new Token(refSym);
        String lexema = token.getLexema();

        tb.inserirSimbolo(lexema, token, line, column, getCodeinfoId());
    }

    public int getCodeinfoId() {
        Yylex scanner = (Yylex) this.getScanner();
        return scanner.codeinfo_id;
    }
 
    public void syntax_error(Symbol s) {     
        this.defineError(s.left, s.right);    
    } 
 
    public void defineError(int line, int column, String text) { 
        Yylex scanner = (Yylex) this.getScanner(); 
        scanner.defineError(line, column, text); 
    } 

    public void defineError(int line, int column) {
        Yylex scanner = (Yylex) this.getScanner(); 
        scanner.defineError(line, column);
    }
  
:}; 

terminal String TEXT, NUMBER;
terminal LEDGER, CLOSE, PAR_OPEN, PAR_CLOSE, PRINT, ID, LET, setaE, KEY_OPEN, 
         KEY_CLOSE, SOMA, SUB, MULT, DIV, RESTO, NOT, DECI, INT, STR, BOO, KEY, NULL, TRUE, FALSE,
         OR, AND, IGUAL, DIF, MAIOR, MENOR, MAIOR_IGUAL, MENOR_IGUAL, IF, ELSE;

non terminal DerivationTree st, stCommand, command, cmdSaida, declaration, atrib, cmdIF, values,
                            tipo, OPR, expr, exprNum, term, OPR_ARITME, OPR_COMP, cmdElse,
                            EPSILON;

st ::= LEDGER:l ID:id stCommand:cmd CLOSE:c {:
    inserirSimbolo(Sym.LEDGER, lleft, lright);
    inserirSimbolo(Sym.ID, id, idleft, idright);
    inserirSimbolo(Sym.CLOSE, cleft, cright);

    List<DerivationTree> lista = new ArrayList<>();
    lista.add( new DerivationTree("LEDGER") );
    lista.add( new DerivationTree("ID", id) );
    lista.add( cmd );
    lista.add( new DerivationTree("CLOSE") );

    RESULT = new DerivationTree("st", lista);
:};

stCommand ::= command:c stCommand:cmd {: 
    List<DerivationTree> lista = new ArrayList<>();
    lista.add( c );
    lista.add( cmd );
    
    RESULT = new DerivationTree("stCommand", lista);
:} | EPSILON:e {: 
    //RESULT = new DerivationTree("stCommand", e);
    // Não fazer nada
:};

command ::= cmdSaida:cs {:
    RESULT = new DerivationTree("command", cs);
:} | declaration:d {:
    RESULT = new DerivationTree("command", d);
:} | atrib:a {:
    RESULT = new DerivationTree("command", a);
:} | cmdIF:ci {:
    RESULT = new DerivationTree("command", ci);
:};

cmdSaida ::= PRINT:p values:v {:
    inserirSimbolo(Sym.PRINT, "$>", pleft, pright);

    List<DerivationTree> lista = new ArrayList<>();
    lista.add( new DerivationTree("PRINT", "$>") );
    lista.add( v );

    RESULT = new DerivationTree("cmdSaida", lista);
:};

declaration ::= LET:l tipo:p ID:id {:
    inserirSimbolo(Sym.LET, lleft, lright);
    inserirSimbolo(Sym.ID, id, idleft, idright);

    List<DerivationTree> lista = new ArrayList<>();
    lista.add( new DerivationTree("LET") );
    lista.add( p );
    lista.add( new DerivationTree("ID", id) );

    RESULT = new DerivationTree("declaration", lista);
:} | LET:l tipo:p ID:id setaE:s values:v {:
    inserirSimbolo(Sym.LET, lleft, lright);
    inserirSimbolo(Sym.ID, id, idleft, idright);
    inserirSimbolo(Sym.setaE, "<-", sleft, sright);
    
    List<DerivationTree> lista = new ArrayList<>();
    lista.add( new DerivationTree("LET") );
    lista.add( p );
    lista.add( new DerivationTree("ID", id) );
    lista.add( new DerivationTree("setaE", "<-") );
    lista.add( v );

    RESULT = new DerivationTree("declaration", lista);
:};

atrib ::= tipo:p ID:id setaE:s values:v {:
    inserirSimbolo(Sym.ID, id, idleft, idright);
    inserirSimbolo(Sym.setaE, "<-", sleft, sright);

    List<DerivationTree> lista = new ArrayList<>();
    lista.add( p );
    lista.add( new DerivationTree("ID", id) );
    lista.add( new DerivationTree("setaE", "<-") );
    lista.add( v );

    RESULT = new DerivationTree("atrib", lista);
:};

tipo ::= DECI:d {:
    inserirSimbolo(Sym.DECI, "$", dleft, dright);

    RESULT = new DerivationTree("tipo", new DerivationTree("DECI", "$"));
:} | INT:i {:
    inserirSimbolo(Sym.INT, "#", ileft, iright);

    RESULT = new DerivationTree("tipo", new DerivationTree("INT", "#"));
:} | STR:s {:
    inserirSimbolo(Sym.STR, "@", sleft, sright);

    RESULT = new DerivationTree("tipo", new DerivationTree("STR", "@"));
:} | BOO:b {:
    inserirSimbolo(Sym.BOO, "?", bleft, bright);

    RESULT = new DerivationTree("tipo", new DerivationTree("BOO", "?"));
:} | KEY:k {:
    inserirSimbolo(Sym.KEY, "!", kleft, kright);

    RESULT = new DerivationTree("tipo", new DerivationTree("KEY", "!"));
:} | NULL:n {:
    inserirSimbolo(Sym.NULL, "~", nleft, nright);

    RESULT = new DerivationTree("tipo", new DerivationTree("NULL", "~"));
:};

values ::= OPR:o {:
    RESULT = new DerivationTree("values", o);
:};

OPR ::= expr:ex {:
    RESULT = new DerivationTree("OPR", ex);
:};

expr ::= expr:ex1 OPR_COMP:oc exprNum:ex2 {:
    List<DerivationTree> lista = new ArrayList<>();
    lista.add( ex1 );
    lista.add( oc );
    lista.add( ex2 );

    RESULT = new DerivationTree("expr", lista);
:} | exprNum:en {:
    RESULT = new DerivationTree("expr", en);
:};

exprNum ::= exprNum:en OPR_ARITME:o term:t {:
    List<DerivationTree> lista = new ArrayList<>();
    lista.add( en );
    lista.add( o );
    lista.add( t );

    RESULT = new DerivationTree("exprNum", lista);
:} | term:t {:
    RESULT = new DerivationTree("exprNum", Arrays.asList(t));
:};


term ::= PAR_OPEN:p1 expr:ex PAR_CLOSE:p2 {:
    inserirSimbolo(Sym.PAR_OPEN, "(", p1left, p1right);
    inserirSimbolo(Sym.PAR_CLOSE, ")", p2left, p2right);

    List<DerivationTree> lista = new ArrayList<>();
    lista.add( new DerivationTree("PAR_OPEN", "(") );
    lista.add( ex );
    lista.add( new DerivationTree("PAR_CLOSE", ")") );

    RESULT = new DerivationTree("term", lista);
:} | NOT:n term:tm {:
    inserirSimbolo(Sym.NOT, "!!", nleft, nright);

    List<DerivationTree> lista = new ArrayList<>();
    lista.add( new DerivationTree("NOT", "!!") );
    lista.add( tm );

    RESULT = new DerivationTree("term", lista);
:} | tipo:p ID:id {:
    inserirSimbolo(Sym.ID, id, idleft, idright);

    List<DerivationTree> lista = new ArrayList<>();
    lista.add( p );

    lista.add( new DerivationTree("ID", id) );
    RESULT = new DerivationTree("term", lista);
:} | NUMBER:n {:
    inserirSimbolo(Sym.NUMBER, n, nleft, nright);

    RESULT = new DerivationTree("term", new DerivationTree("NUMBER", n));
:} | TEXT:t {:
    inserirSimbolo(Sym.TEXT, t, tleft, tright);

    RESULT = new DerivationTree("term", new DerivationTree("TEXT", t));
:} | TRUE:tr {:
    inserirSimbolo(Sym.TRUE, trleft ,trright);

    RESULT = new DerivationTree("term", new DerivationTree("TRUE"));
:} | FALSE:f {:
    inserirSimbolo(Sym.FALSE, fleft, fright);

    RESULT = new DerivationTree("term", new DerivationTree("FALSE"));
:};

OPR_ARITME ::= SOMA:s {:
    inserirSimbolo(Sym.SOMA, "++", sleft, sright);

    RESULT = new DerivationTree("OPR_ARITME", new DerivationTree("SOMA", "++") );
:} | SUB:ss {:
    inserirSimbolo(Sym.SUB, "--", ssleft, ssright);

    RESULT = new DerivationTree("OPR_ARITME", new DerivationTree("SUB", "--") );
:} | DIV:d {:
    inserirSimbolo(Sym.DIV, "//", dleft, dright);

    RESULT = new DerivationTree("OPR_ARITME", new DerivationTree("DIV", "//") );
:} | RESTO:r {:
    inserirSimbolo(Sym.RESTO, "%%", rleft, rright);

    RESULT = new DerivationTree("OPR_ARITME", new DerivationTree("RESTO", "%%") );
:} | MULT:m {:
    inserirSimbolo(Sym.MULT, "**", mleft, mright);

    RESULT = new DerivationTree("OPR_ARITME", new DerivationTree("MULT", "**") );
:};

OPR_COMP ::= OR:o {:
    inserirSimbolo(Sym.OR, "||", oleft, oright);

    RESULT = new DerivationTree("OPR_COMP", new DerivationTree("OR", "||"));
:} | AND:e {:
    inserirSimbolo(Sym.AND, "&&", eleft, eright);

    RESULT = new DerivationTree("OPR_COMP", new DerivationTree("AND", "&&"));
:} | IGUAL:i {:
    inserirSimbolo(Sym.IGUAL, "==", ileft, iright);

    RESULT = new DerivationTree("OPR_COMP", new DerivationTree("IGUAL", "=="));
:} | DIF:d {:
    inserirSimbolo(Sym.DIF, "!=", dleft, dright);

    RESULT = new DerivationTree("OPR_COMP", new DerivationTree("DIF", "!="));
:} | MENOR:mn {:
    inserirSimbolo(Sym.MENOR, "<<", mnleft, mnright);

    RESULT = new DerivationTree("OPR_COMP", new DerivationTree("MENOR", "<<"));
:} | MAIOR:m {:
    inserirSimbolo(Sym.MAIOR, ">>", mleft, mright);

    RESULT = new DerivationTree("OPR_COMP", new DerivationTree("MAIOR", ">>"));
:} | MAIOR_IGUAL:mi {:
    inserirSimbolo(Sym.MAIOR_IGUAL, ">=", mileft, miright);

    RESULT = new DerivationTree("OPR_COMP", new DerivationTree("MAIOR_IGUAL", ">="));
:} | MENOR_IGUAL:mni {:
    inserirSimbolo(Sym.MENOR_IGUAL, "<=", mnileft, mniright);

    RESULT = new DerivationTree("OPR_COMP", new DerivationTree("MENOR_IGUAL", "<="));
:};

cmdIF ::= IF:i PAR_OPEN:p1 OPR:o PAR_CLOSE:p2 KEY_OPEN:k1 stCommand:cmd KEY_CLOSE:k2 cmdElse:se {:
    inserirSimbolo(Sym.IF, ileft, iright);
    inserirSimbolo(Sym.PAR_OPEN, "(", p1left, p1right);
    inserirSimbolo(Sym.PAR_CLOSE, ")", p2left, p2right);
    inserirSimbolo(Sym.KEY_OPEN, "{", k1left, k1right);
    inserirSimbolo(Sym.KEY_CLOSE, "}", k2left, k2right);

    List<DerivationTree> lista = new ArrayList<>();
    lista.add( new DerivationTree("IF") );
    lista.add( new DerivationTree("PAR_OPEN", "(") );
    lista.add( o );
    lista.add( new DerivationTree("PAR_CLOSE", ")") );
    lista.add( new DerivationTree("KEY_OPEN", "{") );
    lista.add( cmd );
    lista.add( new DerivationTree("KEY_CLOSE", "}") );
    lista.add( se );

    RESULT = new DerivationTree("cmdIF", lista);
:};
cmdElse ::= ELSE:se KEY_OPEN:k1 stCommand:cmd KEY_CLOSE:k2 {:
    inserirSimbolo(Sym.ELSE, seleft, seright);
    inserirSimbolo(Sym.KEY_OPEN, "{", k1left, k1right);
    inserirSimbolo(Sym.KEY_CLOSE, "}", k2left, k2right);

    List<DerivationTree> lista = new ArrayList<>();
    lista.add( new DerivationTree("ELSE") );
    lista.add( new DerivationTree("KEY_OPEN", "{") );
    lista.add( cmd );
    lista.add( new DerivationTree("KEY_CLOSE", "}") );

    RESULT = new DerivationTree("cmdElse", lista);
:} | EPSILON {:
    // Não fazer nada
:};


EPSILON ::= {:
    //inserirSimbolo(Sym.EPSILON);
    // Não fazer nada
:};

