
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.faria;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int COMMA = 7;
  public static final int PAR_OPEN = 4;
  public static final int SEMICOLON = 6;
  public static final int PAR_CLOSE = 5;
  public static final int error = 1;
  public static final int NUMBER = 2;
  public static final int TRIANGULO = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "TRIANGULO",
  "PAR_OPEN",
  "PAR_CLOSE",
  "SEMICOLON",
  "COMMA"
  };
}

